name: flutter_power_file_preview
description: A local file view widget, support a variety of file types, such as Doc Eexcl PPT TXT PDF and so on, Android is implemented by Tencent X5, iOS is implemented by WKWebView
version: 0.0.1
homepage: https://github.com/vvkeep/flutter_power_file_preview

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: cn.vvkeep.flutter_power_file_preview
        pluginClass: FlutterPowerFilePreviewPlugin
      ios:
        pluginClass: FlutterPowerFilePreviewPlugin

